### PR TITLE
Peds 1307

### PR DESCRIPTION
**Pull request by paulmurdoch19**

### CODE REVIEW

**Comment by grugna** [comment]
@paulmurdoch19 thank you for updating that. Were the other dependencies up to date?

**Comment by paulmurdoch19** [comment]
Let me go through and check I just ran poetry update

**Comment by paulmurdoch19** [comment]
I went through it and removed all the packages that were not actually being used by amanuensis and moved sqlalchemy to the latest version which required the execute function to use the text function.

NOTE: dont merge till userportaldatamodel is updated

**Comment by grugna** [comment]
new version for userportaldatamodel is 1.7.0

**Comment by paulmurdoch19** [comment]
version update and synced with pcdc_dev

**Pull request merged**
